# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/marc/cuda-workspace/MicrovolutionPython/conda.recipe, last modified Mon Jun 15 17:28:51 2020
# ------------------------------------------------

package:
    name: microvolution_py
    version: '2020.04'
source:
    path: /home/marc/cuda-workspace/MicrovolutionPython
build:
    binary_relocation: true
    number: '3'
    rpaths:
        - lib
    string: py3.6_numpy1.18_cuda10.1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he6710b0_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - blas 1.0 mkl
        - bzip2 1.0.8 h7b6447c_0
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - cmake 3.14.0 h52cb24c_0
        - expat 2.2.6 he6710b0_0
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_15
        - intel-openmp 2020.1 217
        - krb5 1.17.1 h173b8e3_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libcurl 7.69.1 h20c2e04_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libssh2 1.9.0 h1ba5d50_1
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.1 217
        - mkl-service 2.3.0 py36he904b0f_0
        - mkl_fft 1.0.15 py36ha843d7b_0
        - mkl_random 1.1.1 py36h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.18.1 py36h4f9e942_0
        - numpy-base 1.18.1 py36hde5b4d6_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - pybind11 2.4.3 py36hfd86e86_0
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - rhash 1.3.8 h1ba5d50_0
        - setuptools 47.1.1 py36_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    host:
        - _libgcc_mutex 0.1 main
        - blas 1.0 mkl
        - ca-certificates 2020.1.1 0
        - certifi 2020.4.5.1 py36_0
        - intel-openmp 2020.1 217
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.3 he6710b0_1
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - mkl 2020.1 217
        - mkl-service 2.3.0 py36he904b0f_0
        - mkl_fft 1.0.15 py36ha843d7b_0
        - mkl_random 1.1.1 py36h0573a6f_0
        - ncurses 6.2 he6710b0_1
        - numpy 1.18.1 py36h4f9e942_0
        - numpy-base 1.18.1 py36hde5b4d6_1
        - openssl 1.1.1g h7b6447c_0
        - pip 20.0.2 py36_3
        - python 3.6.10 h7579374_2
        - readline 8.0 h7b6447c_0
        - setuptools 47.1.1 py36_0
        - six 1.15.0 py_0
        - sqlite 3.31.1 h62c20be_1
        - tk 8.6.8 hbc83047_0
        - wheel 0.34.2 py36_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.18,<1.19.0a0
        - python >=3.6,<3.7.0a0
about:
    license_file: LICENSE
    summary: Microvolution wrapper in Python
extra:
    copy_test_source_files: true
    final: true
